FROM python:3.11-slim

WORKDIR /app

COPY requirements-dev.txt .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]